name: Trigger A Repo Build

on:
  push:
    branches:
      - main  # 监听 B 库的主分支更新，确保 B 库的更新能够触发这个工作流

jobs:
  trigger-build:
    runs-on: ubuntu-latest

    steps:
      # 1. 触发 A 库的构建
      - name: Trigger A Repo Build
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: 'Joker2184/HomepageBuilder'  # A 库的 GitHub 仓库名
          token: ${{ secrets.PAT_TOKEN }}  # 使用 GitHub 自动生成的 PAT 令牌进行授权
          event-type: trigger-a-build  # A 库触发的事件类型，可以自定义，这里是 trigger-a-build
