name: UpdateHP-Get

on:
  push:
    branches:
      - main  # 监听 B 仓库的主分支更新

jobs:
  check-pcl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run update script
        id: run_script
        run: sh Actions/CheckPCLVersion.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# 配置 `Trigger A and C Repo Builds` 工作流
name: Trigger A and C Repo Builds

on:
  push:
    branches:
      - main  # 监听 B 仓库的主分支更新

jobs:
  trigger-builds:
    runs-on: ubuntu-latest

    steps:
      # 触发 A 仓库（HomepageBuilder）的构建
      - name: Trigger A Repo Build
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: 'Joker2184/HomepageBuilder'  # A 仓库的 GitHub 仓库名
          token: ${{ secrets.PAT_TOKEN }}  # 使用 GitHub 自动生成的 PAT 令牌进行授权
          event-type: trigger-a-build  # A 仓库触发的事件类型，可以自定义，这里是 trigger-a-build

      # 触发 D 仓库（UpdateHP-Built-Modules）的构建
      - name: Trigger C Repo Build
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: 'Joker2184/UpdateHP-Built-Modules'  # C 仓库的 GitHub 仓库名
          token: ${{ secrets.PAT_TOKEN }}  # 使用 GitHub 自动生成的 PAT 令牌进行授权
          event-type: trigger-d-build  # D 仓库触发的事件类型，可以自定义，这里是 trigger-d-build

  # 触发 `Trigger A and C Repo Builds` 工作流
  trigger-repo-build:
    runs-on: ubuntu-latest
    needs: check-pcl
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, 'Update PCL version file') }}
    steps:
      - name: Trigger A and C Builds
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: 'Joker2184/Trigger-A-and-C-Repo-Builds'  # 配置文件所在仓库
          token: ${{ secrets.PAT_TOKEN }}
          event-type: trigger-a-c-build
