# 触发规则
on:
  schedule:
    - cron: "*/10 * * * *"  # 每 10 分钟触发一次
  workflow_dispatch:  # 手动触发工作流

jobs:
  update_pr_list:
    runs-on: ubuntu-latest  # 在 Ubuntu 环境下运行

    steps:
    # 1. Checkout UpdateHomepage-Build 仓库
    - name: Checkout UpdateHomepage-Build repository
      uses: actions/checkout@v2
      with:
        repository: Joker2184/UpdateHomepage-Build
        path: UpdateHomepage-Build  # 将该仓库代码检出到子目录

    # 2. 展示根目录的文件结构
    - name: List files in the root directory
      run: |
        ls -R  # 列出根目录的所有文件及子目录

    # 3. 拉取最新的代码 (避免冲突)
    - name: Pull latest changes from UpdateHomepage-Build
      run: |
        cd UpdateHomepage-Build
        git pull origin main  # 拉取最新的主分支代码

    # 4. 删除现有的 PRList.xaml 文件
    - name: Delete existing PRList.xaml in UpdateHomepage-Build
      run: |
        rm -f ./libraries/Homepage/PRList.xaml  # 删除旧文件

    # 5. 安装 Python 环境和依赖
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # 设置 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests  # 安装 requests 库

    # 6. 运行 Python 脚本生成新的 PRList.xaml 文件
    - name: Run Python script to generate PRList.xaml
      env:
         PAT_TOKEN: ${{ secrets.PAT_TOKEN }}  # 使用 GitHub Token 作为环境变量
      run: |
        cd UpdateHomepage-Build/Actions  # 进入 Python 脚本所在的目录
        python GetPRList.py  # 运行 Python 脚本生成 PRList.xaml 文件

    # 7. 设置 git 用户凭证
    - name: Set up git user credentials
      run: |
        git config --global user.name "Joker2184Bot"
        git config --global user.email "Joker2184@outlook.com"


    # 9. 检查 Git 状态，确保文件已经被跟踪
    - name: Check git status
      run: |
        cd UpdateHomepage-Build
        git status

    # 10. 提交并推送 PRList.xaml 文件到 UpdateHomepage-Build 仓库
    - name: Commit and push PRList.xaml to UpdateHomepage-Build
      run: |
        cd UpdateHomepage-Build
        git add libraries/Homepage/PRList.xaml  # 添加文件
        git commit -m "Update PRList.xaml"  # 提交
        git push origin main  # 推送到 main 分支
