name: UpdateHP-Get

on:
  push:
    branches:
      - main  # 监听 B 库的主分支更新

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository-dispatch in another repo
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: 'username/repo-B'  # 替换为目标仓库
          token: ${{ secrets.PAT_Token }}  # 使用 PAT
          event-type: 'build-trigger'  # 触发事件类型（根据目标仓库设置）

