name: UpdateHP-Get

on:
  push:
    branches:
      - main  # 监听 B 库的主分支更新
      
jobs:
  trigger-build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger A Repo Build
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: 'Joker2184/HomepageBuilder'
          token: ${{ secrets.PAT_TOKEN }}
          event-type: trigger-a-build
      - name: Debug information
        run: |
          echo "调试信息"
          echo "是否成功触发 A 库构建？"
