name: Get PR List and Update Homepage

# 触发规则
on:
  schedule:
    - cron: "*/10 * * * *"  # 每 10 分钟触发一次
  workflow_dispatch:  # 手动触发工作流

jobs:
  update_pr_list:
    runs-on: ubuntu-latest  # 在 Ubuntu 环境下运行

    steps:
    # 1. Checkout UpdateHomepage-Build 仓库
    - name: Checkout UpdateHomepage-Build repository
      uses: actions/checkout@v2
      with:
        repository: Joker2184/UpdateHomepage-Build
        path: UpdateHomepage-Build  # 将该仓库代码检出到子目录

    # 2. 拉取最新的代码 (避免冲突)
    - name: Pull latest changes from UpdateHomepage-Build
      run: |
        cd UpdateHomepage-Build
        git pull origin main  # 拉取最新的主分支代码

    # 3. 删除现有的 PRList.xaml 文件
    - name: Delete existing PRList.xaml in UpdateHomepage-Build
      run: |
        rm -f UpdateHomepage-Build/libraries/Homepage/PRList.xaml  # 删除旧文件

    # 4. 安装 Python 环境和依赖
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # 设置 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests  # 安装 requests 库

    # 5. 运行 Python 脚本生成新的 PRList.xaml 文件
    - name: Run Python script to generate PRList.xaml
      env:
         PAT_TOKEN: ${{ secrets.PAT_TOKEN }}  # 使用 GitHub Token 作为环境变量
      run: |
        cd UpdateHomepage-Build/Actions  # 进入 Python 脚本所在的目录
        python GetPRList.py  # 运行 Python 脚本生成 PRList.xaml 文件

    # 6. 检查 git 状态，确保文件被正确添加
    - name: Check git status
      run: |
        cd UpdateHomepage-Build
        git status  # 查看当前状态，确认文件是否已添加

    # 7. 提交并推送 PRList.xaml 文件到 UpdateHomepage-Build 仓库
    - name: Commit changes to UpdateHomepage-Build
      run: |
        cd UpdateHomepage-Build
        git add libraries/Homepage/PRList.xaml  # 添加新的文件
        git commit -m "Update PR list"  # 提交更新
        git status  # 检查是否有提交

    # 8. 推送更新到 GitHub 仓库
    - name: Push changes to UpdateHomepage-Build repository
      run: |
        cd UpdateHomepage-Build
        git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/Joker2184/UpdateHomepage-Build.git HEAD:main  # 推送到目标仓库的 main 分支

    # 9. 提交成功后，确认文件已经推送
    - name: Confirm changes pushed to GitHub
      run: |
        git pull origin main  # 拉取远程更新
        git log -n 1  # 查看最新的提交日志，确认是否已经提交
