name: Check PCL Version
on:
   schedule:
    - cron: '0/15 * * * *'
   workflow_dispatch:
      
jobs:
   check-pcl:
      runs-on: ubuntu-latest
      steps:
       - name: 签出储存库
         uses: actions/checkout@v4
       - name: 运行更新脚本
         id: run_script
         run: bash Actions/CheckPCLVersion.sh
         env:
            PAT_TOKEN: ${{ secrets.PAT_TOKEN }}  # 传递 PAT_TOKEN 环境变量
            GH_TOKEN: ${{ github.token }}  # 设置 GitHub 自动生成的 GH_TOKEN
